name: CI/CD

on:
  push:
    branches:
      - main
      - '*'

env:
  REGISTRY: 6l20registry.azurecr.io
  APP_NAME: tiny-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and test
      run: |
        go build -o main .
        go test ./...

    - name: Build Docker image
      run: docker build -t ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} .

    - name: Login to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Development
      if: github.ref != 'refs/heads/main'
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az aks get-credentials --resource-group 6l20rgroup --name 6l20cluster --overwrite-existing
        helm upgrade --install --wait --namespace development --create-namespace development tiny-backend-chart --set image.tag=${{ github.sha }}

    - name: Deploy to Staging
      if: github.ref == 'refs/heads/main'
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az aks get-credentials --resource-group 6l20rgroup --name 6l20cluster --overwrite-existing
        helm upgrade --install --wait --namespace staging --create-namespace staging tiny-backend-chart --set image.tag=${{ github.sha }}

